spring.application.name=bank-notification

server.port=8081

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.retry.multiplier=2

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saidxonov.mahmud11@gmail.com
spring.mail.password=ysukdweafeapceod
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

internal.secret.key=my-internal-secret-bank-key-mg1112